name: Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.0", "8.1", "8.2", "8.3"]
        typo3-version: ["11.5", "12.4", "13.3"]
        dependencies: ["highest", "lowest"]
        exclude:
          - php-version: "8.0"
            typo3-version: "12.4"
          - php-version: "8.0"
            typo3-version: "13.3"
          - php-version: "8.1"
            typo3-version: "13.3"
    env:
      DB_DATABASE: typo3
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      # Install Composer dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: "--with=typo3/cms-core:^${{ matrix.typo3-version }}"

      # Run tests
      - name: Run tests
        run: composer test
        env:
          typo3DatabaseName: ${{ env.DB_DATABASE }}
          typo3DatabaseHost: 127.0.0.1
          typo3DatabasePort: ${{ job.services.mysql.ports[3306] }}
          typo3DatabaseUsername: ${{ env.DB_USER }}
          typo3DatabasePassword: ${{ env.DB_PASSWORD }}

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: typo3
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: pcov

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      # Install Composer dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Run tests
      - name: Run tests
        run: composer test -- --coverage-text
        env:
          typo3DatabaseName: ${{ env.DB_DATABASE }}
          typo3DatabaseHost: 127.0.0.1
          typo3DatabasePort: ${{ job.services.mysql.ports[3306] }}
          typo3DatabaseUsername: ${{ env.DB_USER }}
          typo3DatabasePassword: ${{ env.DB_PASSWORD }}

      # Build coverage report
      - name: Generate coverage report
        run: composer test:coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
