name: Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.0", "8.1", "8.2"]
        typo3-version: ["11.5", "12.2"]
        dependencies: ["highest", "lowest"]
        exclude:
          - php-version: "8.0"
            typo3-version: "12.2"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: typo3
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      # Install Composer dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: "--with=typo3/cms-core:^${{ matrix.typo3-version }}"

      # Run tests
      - name: Run tests
        run: composer test
        env:
          typo3DatabaseName: typo3
          typo3DatabaseHost: 127.0.0.1
          typo3DatabasePort: ${{ job.services.mysql.ports[3306] }}
          typo3DatabaseUsername: root
          typo3DatabasePassword: root

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: typo3
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: pcov

      # Install Composer dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Run tests
      - name: Run tests
        run: composer test -- --coverage-text
        env:
          typo3DatabaseName: typo3
          typo3DatabaseHost: 127.0.0.1
          typo3DatabasePort: ${{ job.services.mysql.ports[3306] }}
          typo3DatabaseUsername: root
          typo3DatabasePassword: root

      # Build coverage report
      - name: Generate coverage report
        run: composer test:coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
